2023-08-03 23:30:38,235 - DEBUG - This is a debug message
2023-08-03 23:30:38,239 - ERROR - This is an error message
2023-08-03 23:30:38,242 - ERROR - An error occurred while dividing by zero:
Traceback (most recent call last):
  File "/tmp/ipykernel_67526/468990844.py", line 19, in <module>
    result = 10 / 0
             ~~~^~~
ZeroDivisionError: division by zero
